//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace dym.Model
{
    /// <summary>
    /// 实体类bif_company。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    public class bif_company
    {
        /// <summary>
        /// auto_increment
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string code { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string tel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string fax { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string zip { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string email { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string website { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string person { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? state { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? rdt { get; set; }
    }
}